[package]
name = "rustcord"
version = "0.1.2"
edition = "2021"

[dependencies]
regex = "1.11.0"
dotenv = "0.15.0"
serenity = "0.12.2"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "postgres", "uuid", "time" ] }
uuid = { version = "1.10.0", features = ["v4"] }
log = "0.4.22"
env_logger = "0.11.5"
unicode-normalization = "0.1.24"
once_cell = "1.20.2"

[dev-dependencies]
pre-commit = "0.5.2"

[package.metadata.precommit]
fmt = "cargo fmt -- --write-mode diff 2>&1"
clippy = "cargo clippy -- -D warning 2>&1"
test = "cargo test 2>&1"