[package]
name = "rustcord"
version = "0.1.2"
edition = "2021"

[dependencies]
regex = "1.11.0"
dotenv = "0.15.0"
serenity = "0.12.2"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "postgres", "uuid", "time" ] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
log = "0.4.22"
env_logger = "0.11.5"
unicode-normalization = "0.1.24"
redis = { version = "0.31.0", features = ["tokio-comp"] }
serde = { version = "1.0.219", features = ["derive"] }
ron = "0.10.1"
async-dropper = { version = "0.3", features = [ "tokio", "simple" ] }
async-trait = "0.1.88"
thiserror = "2.0.12"
anyhow = "1.0.98"