[package]
name = "rustcord"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.0"
dotenv = "0.15.0"
serenity = "0.12.2"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12.8", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "postgres", "uuid" ] }
uuid = { version = "1.10.0", features = ["v4"] }
log = "0.4.22"
env_logger = "0.11.5"
rayon = "1.10.0"
unicode-normalization = "0.1.24"
once_cell = "1.20.2"