[package]
name = "rustcord"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.0"
dotenv = "0.15.0"
serenity = "0.12.2"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
lazy_static = "1.5.0"
reqwest = "0.12.8"