DROP TABLE IF EXISTS related_token;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS combo;
DROP TABLE IF EXISTS card;
DROP TABLE IF EXISTS set;
DROP TABLE IF EXISTS rule;
DROP TABLE IF EXISTS legality;
DROP TABLE IF EXISTS illustration;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS artist;

DROP EXTENSION IF EXISTS pg_trgm;