UPSERT = """
         INSERT INTO legality
         (id,
          alchemy,
          brawl,
          commander,
          duel,
          future,
          gladiator,
          historic,
          legacy,
          modern,
          oathbreaker,
          oldschool, pauper,
          paupercommander,
          penny,
          pioneer,
          predh,
          premodern,
          standard,
          standardbrawl,
          timeless,
          vintage,
          game_changer)
         VALUES ($1,
                 $2,
                 $3,
                 $4,
                 $5,
                 $6,
                 $7,
                 $8,
                 $9,
                 $10,
                 $11,
                 $12,
                 $13,
                 $14,
                 $15,
                 $16,
                 $17,
                 $18,
                 $19,
                 $20,
                 $21,
                 $22,
                 $23)
         ON CONFLICT(id) DO UPDATE SET alchemy         = EXCLUDED.alchemy,
                                       brawl           = EXCLUDED.brawl,
                                       commander       = EXCLUDED.commander,
                                       duel            = EXCLUDED.duel,
                                       future          = EXCLUDED.future,
                                       gladiator       = EXCLUDED.gladiator,
                                       historic        = EXCLUDED.historic,
                                       legacy          = EXCLUDED.legacy,
                                       modern          = EXCLUDED.modern,
                                       oathbreaker     = EXCLUDED.oathbreaker,
                                       oldschool       = EXCLUDED.oldschool,
                                       pauper          = EXCLUDED.pauper,
                                       paupercommander = EXCLUDED.paupercommander,
                                       penny           = EXCLUDED.penny,
                                       pioneer         = EXCLUDED.pioneer,
                                       premodern       = EXCLUDED.premodern,
                                       standard        = EXCLUDED.standard,
                                       standardbrawl   = EXCLUDED.standardbrawl,
                                       timeless        = EXCLUDED.timeless,
                                       vintage         = EXCLUDED.vintage,
                                       game_changer    = EXCLUDED.game_changer;
         """
