apiVersion: batch/v1
kind: Job
metadata:
  name: db-update
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: db-migrate
          image: gitfrog/rustcord-db-management:latest
          command: ["/app/.venv/bin/alembic", "upgrade", "head"]
          env:
            - name: PSQL_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PSQL_URI
      containers:
        - name: card-insert
          image: gitfrog/rustcord-db-management:latest
          command: ["/app/.venv/bin/python", "main.py"]
          env:
            - name: PSQL_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PSQL_URI
            - name: IMAGES_DIR
              value: /var/mtg_cards
          volumeMounts:
            - name: images
              mountPath: /var/mtg_cards
      volumes:
        - name: images
          hostPath:
            path: /var/mtg_cards/

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: card-insert

spec:
  schedule: "0 6 * * 3"  # Wednesday 06:00 UTC
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: card-insert
              image: gitfrog/rustcord-db-management:latest
              command: ["/app/.venv/bin/python", "main.py"]
              env:
                - name: PSQL_URI
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets
                      key: PSQL_URI
                - name: IMAGES_DIR
                  value: /var/mtg_cards
              volumeMounts:
                - name: images
                  mountPath: /var/mtg_cards

          volumes:
            - name: images
              hostPath:
                path: /var/mtg_cards/
