apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    type: bot
    app: discord

spec:
  replicas: 1
  selector:
    matchLabels:
      type: bot
      app: discord
  template:
    metadata:
      labels:
        type: bot
        app: discord
    spec:
      containers:
        - name: rustcord
          image: gitfrog/rustcord:latest
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOT_TOKEN
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PW
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: IMAGES_DIR
              value: /var/mtg_cards
            - name: RUST_LOG
              value: warn,rustcord=info
          volumeMounts:
            - name: images
              mountPath: /var/mtg_cards/
              readOnly: true
      volumes:
        - name: images
          hostPath:
            path: /var/mtg_cards/
