apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    type: notifier
    app: discord

spec:
  replicas: 1
  selector:
    matchLabels:
      type: notifier
      app: discord
  template:
    metadata:
      labels:
        type: notifier
        app: discord
    spec:
      containers:
        - name: notifier
          image: gitfrog/rustcord-notifier:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PW
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_HOST
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOT_TOKEN
            - name: RUST_LOG
              value: warn,notifier=info,cards_sdk=info
