apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    service: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PW
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service

spec:
  selector:
    service: postgres
  ports:
    - port: 5432
      targetPort: 5432
