name: Deploy The Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-db-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -f packages/db/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rustcord-db-management .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord-db-management:latest

  build-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -f packages/bot/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rustcord .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord:latest

  deploy:
    needs:
      - build-bot
      - build-db-management
    if: always() && needs.build-bot.result == 'success' && (needs.build-db-management.result == 'success' || needs.build-db-management.result == 'skipped')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Apply Secrets
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PW=${{ secrets.POSTGRES_PW }} \
            --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            --from-literal=POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            --from-literal=IMAGES_DIR=${{ secrets.IMAGES_DIR }} \
            --from-literal=REDIS_URL=${{ secrets.REDIS_URL }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply
        run: kubectl apply -f k8s/
