name: Deploy The Bot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/rustcord .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rustcord:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Image From Docker
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/rustcord:latest

      - name: Delete Old Container
        run: docker rm -f rustcord-container
        continue-on-error: true

      - name: Run Docker Container
        run: |
          docker run -d \
          --name rustcord-container \
          --restart=always \
          --add-host=host.docker.internal:host-gateway \
          -v ${{ secrets.HOST_IMAGE_DIR }}:${{ secrets.IMAGE_DIR }} \
          -e BOT_TOKEN='${{ secrets.BOT_TOKEN }}' \
          -e PQSL_URI='${{ secrets.PSQL_URI }}' \
          -e IMAGES_DIR='${{ secrets.IMAGES_DIR }}' \
          -e RUST_LOG='${{ secrets.RUST_LOG }}' \
          -e REDIS_URL='${{ secrets.REDIS_URL }}' \
          ${{ secrets.DOCKER_USERNAME }}/rustcord:latest
