name: bulk-sync

on:
  workflow_dispatch:

jobs:
  bulk-sync:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trigger bulk-sync job
        run: kubectl create job --from=cronjob/bulk-sync bulk-sync-manual