name: insert-cards

on:
  workflow_dispatch:

jobs:
  insert:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Trigger card-insert job
        run: kubectl create job --from=cronjob/card-insert card-insert-manual
